language: python

python: 
  - "3.6"

env:
  - DJANGO_SETTINGS_MODULE=""
  - DJANGO_SETTINGS_MODULE=""

install:
  - pip install -r requirements.txt

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test

