# Generated by Django 2.1.5 on 2019-12-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191206_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_secondary_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_secondary_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_secondary_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
